[package]
name = "PasswordManager"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = "0.5.3"
clap = {version="4", features=["derive"]}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.140"
