[package]
name = "PswrdMngrREPL"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.37"
rustyline = "15.0.0"
serde = { version = "1.0", features = ["derive"] }
bincode = "2.0.1"
aes-gcm = { version = "0.10", features = ["std"] }
aes = "0.8"
rand = "0.9.1"
hex = "0.4"
